import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/icons/favicon.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} container flex flex-col h-screen items-center`}>
        <div className='w-full border-2 p-6'>Navbar</div>
        <main className='flex-1 w-full border-2 p-6'>{children}</main>
        <div className='w-full border-2 p-6'>Footer</div>
      </body>
    </html>
  )
}
